export const cardsData = [
    {
        id:1,
        title: "Task 1",
        datetime: "25/1/2022 10:40 hrs",
        creator:"Juan Perez",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
        type: "inProcess",
        priority: "high",
    },
    {
        id:2,
        title: "Task 2",
        datetime: "28/1/2022 10:40 hrs",
        creator:"Norberto Ruiz",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
        type: "inProcess",
        priority: "high",
    },
    {
        id:3,
        title: "Task 3",
        datetime: "25/1/2022 12:40 hrs",
        creator:"Cherquis Bialo",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
        type: "inProcess",
        priority: "high",
    },
    {
        id:4,
        title: "Task 4",
        datetime: "25/1/2022 12:45 hrs",
        creator:"Maravilla Martinez",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
        type: "inProcess",
        priority: "low",
    },
    {
        id:5,
        title: "Task 5",
        datetime: "25/1/2022 10:50 hrs",
        creator:"Santiago Castro",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
        type: "finished",
        priority: "high",
    },
    {
        id:6,
        title: "Task 6",
        datetime: "25/1/2022 10:40 hrs",
        creator:"Santiago Castro",
        description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
        type: "new",
        priority: "high",
    },
]